name: daco
repository: https://github.com/blaugold/daco
packages:
  - 'packages/**'
ignore:
  - 'packages/daco/tools/analyzer_plugin/**'

ide:
  intellij: false

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    linkToCommits: true
    branch: main

scripts:
  activate:
    description: Activates the local version of daco globally.
    exec: dart pub global activate --source path . --overwrite
    select-package:
      scope: daco

  format:
    description: Formats Dart code in the repository with daco.
    run: daco format .

  format-check:
    description: Checks formatting of Dart code in the repository with daco.
    run: daco format --set-exit-if-changed .

  analyze:
    description: Analyzes Dart packages in the repository.
    exec: dart analyze --fatal-infos --fatal-warnings

  test:
    description: Runs tests.
    run: dart test
    exec:
      concurrency: 1

  build:prettier_server: cd packages/daco/prettier-server && npm run build
