name: daco_analyzer_plugin
publish_to: none

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  # daco: any # TODO: automate updating to the exact version of daco
  analyzer_plugin: ^0.11.0
  web_socket_channel: ^2.2.0
