name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Setup daco
        run: dart pub global activate daco
      - name: Check formatting of Dart code
        run: melos format:check

  analyze:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Bootstrap
        run: melos bootstrap
      - name: Analyze Dart packages
        run: melos analyze

  test:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Setup daco
        run: dart pub global activate daco
      - name: Run tests
        run: melos test --no-select
