name: daco
description:
  A tool for maintaining Dart comments. Supports formatting of comments,
  including embedded Dart code.
version: 0.2.3+1
homepage: https://github.com/blaugold/daco/tree/main/packages/daco
repository: https://github.com/blaugold/daco
issue_tracker: https://github.com/blaugold/daco/issues

environment:
  sdk: '>=2.17.1 <3.0.0'

executables:
  daco: cli

dependencies:
  _fe_analyzer_shared: ^40.0.0
  analyzer: ^4.1.0
  analyzer_plugin: ^0.11.0
  ansi_styles: ^0.3.2+1
  args: ^2.3.1
  cli_util: ^0.3.5
  collection: ^1.16.0
  dart_style: ^2.2.3
  http: ^0.13.4
  path: ^1.8.0
  pubspec_parse: ^1.2.0
  solvent: ^0.1.1
  synchronized: ^3.0.0+2

dev_dependencies:
  term_glyph: ^1.2.0
  test: ^1.16.0
